### ISSUE TITLE
META: Implement norms review in extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#101]
Continuing from https://github.com/open-contracting/standard/issues/830

[This spreadsheet](https://docs.google.com/spreadsheets/d/1QuVTr8Vn9w1aM5_ba-f2fcwYkmt6l3y4qG0v3t7WL_Y/edit#gid=0) has three sheets of reviewed norms in extensions. (The separate, summary document has no content relating to extensions.)

Non-normative keywords are https://tools.ietf.org/html/draft-hansen-nonkeywords-non2119-03

* [x] Check for occurrences of normative keywords followed by "always", "only", "consider" or "generally", like in `Item.relatedLot`.

The `must|require(?!d":)|\bshall|should|recommend|\bmay\b|optional` (case-insensitive) regular expression can be used to find normative keywords and `need|necessary|ought|encourage|suggest|\bcan\b|might|allow|permit` for non-normative keywords.

All extensions:

* [x] Normative words in codelists
* [x] Non-normative words in codelists

Core extensions:

* [ ] Normative words in readme
* [ ] Non-normative words in readme
* [x] Normative words in schema
* [x] Non-normative words in schema

Community extensions:

* [ ] Normative words in readme
* [ ] Non-normative words in readme
* [ ] Normative words in schema
* [ ] Non-normative words in schema

**Comment by romifz** [comment]
Hi James,

Sorry if this sounds silly, but is the task here to go through the linked spreadsheet and mark the normative keywords followed by "always", "only", "consider" or "generally" only? Why it is necessary to look for non-normative keywords?

**Comment by jpmckinney** [comment]
The task is to go through all extensions and (1) check that normative words are used correctly and (2) check that non-normative words aren't accidentally used where a normative word should be.

I just grepped the JSON files in extensions and found over 100 matches for `description.*?(must|require(?!ment)|shall|should|recommend|may|optional)`.

I think it might be best for me to review those matches, as I'll have to spend almost the same amount of time reviewing others' changes.

**Comment by duncandewhurst** [comment]
@jpmckinney is this something that @odscjen could pick up or do you still want to review the matches yourself?

**Comment by jpmckinney** [comment]
I'm not sure why the checkboxes for "core" extension readmes aren't checked; the linked spreadsheet covers readmes.

Assuming that's done, I'll close this issue, as normative review of extensions that are outside the governance process is out-of-scope.

There are many ways in which those extensions can be improved. We tend to address them when making changes for other reasons (e.g. we'll improve style guide alignment when adding a new field to an extension).
