### ISSUE TITLE
META: Add examples to remaining extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#120]
* [x] ocds_api_extension
* [x] ocds_contract_suppliers_extension
* [x] ocds_documentation_extension
* [x] ocds_milestone_documents_extension

**Comment by jpmckinney** [comment]
@yolile FYI, for the documentation extension, you can continue https://github.com/open-contracting/ocds-extensions/issues/120

**Comment by yolile** [comment]
@jpmckinney do you mean [#18](https://github.com/open-contracting-extensions/ocds_documentation_extension/pull/18) ?

**Comment by jpmckinney** [comment]
Yes, sorry :)

**Comment by jpmckinney** [comment]
:tada:
