### ISSUE TITLE
META: Have examples in all READMEs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#34]
~~And then include them in docs with `jsoninclude` directive.~~

* [x] charges (PPP)
* [ ] ~~contract_suppliers~~ #86
* [ ] ~~documentation_details (PPP)~~ #84
* [x] finance ([example in the PPP sample data](https://github.com/open-contracting-extensions/public-private-partnerships/blob/e9c8d724b7fc9b4927f2aa979fb7e1e7f4152cb6/docs/examples/full_record_package.json#L2915))
* [ ] milestone_documents (nothing in 1.0, need new example)
* [x] process_title (PPP)
* [x] qualification (PPP)
* [x] risk_allocation (PPP)
* [x] shareholders (PPP)

We should ideally test that the example validates (see open-contracting/standard-maintenance-scripts#24)

**Comment by jpmckinney** [comment]
We'll go with option (1) as we don't have an obvious solution for merging the example into the readme without adding an extra step for extension authors.

**Comment by duncandewhurst** [comment]
We should be able to extract examples from the PPP sample data for charges, documentation_details, finance, qualification, risk_allocation, shareholders and (I think) process_title.

**Comment by jpmckinney** [comment]
I added examples for 6 extensions, created blocking issues for 2 extensions, and will create a follow-up issue for milestone documents, which had no readily available example.
