### ISSUE TITLE
META: Missing fields in schema

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#40]
Blocking https://github.com/open-contracting/standard-maintenance-scripts/issues/27

50 fields missing in 9 extensions.

## Core

ocds_participationFee_extension/release-schema.json

* [x] /definitions/ParticipationFee/description
* [x] /definitions/ParticipationFee/properties/value/title
* [x] /definitions/ParticipationFee/properties/value/description

ocds_location_extension/release-schema.json

* [x] /definitions/Item/properties/deliveryLocation/description
* [x] /definitions/Item/properties/deliveryAddress/description
* [x] /definitions/Location/properties/gazetteer/title
* [x] /definitions/Location/properties/gazetteer/description

ocds_lots_extension/release-schema.json

* [x] /definitions/Tender/properties/lotDetails/title
* [x] /definitions/Tender/properties/lotDetails/description

### PPPs

ocds_budget_projects_extension/release-schema.json

* [x] /definitions/Planning/properties/project/title
* [x] /definitions/Planning/properties/project/description
* [x] /definitions/Project/properties/id/title
* [x] /definitions/Project/properties/totalValue/title

ocds_finance_extension/release-schema.json

* [x] /definitions/Finance/properties/financingParty/title
* [x] /definitions/Finance/properties/financingParty/description

ocds_metrics_extension/release-schema.json

* [x] /definitions/Observation/properties/period/title
* [x] /definitions/Observation/properties/period/description
* [x] /definitions/Observation/properties/value/title
* [x] /definitions/Observation/properties/value/description

ocds_performance_failures/release-schema.json

* [x] /definitions/Implementation/properties/performanceFailures/description

ocds_requirements_extension/release-schema.json

* [x] /definitions/Tender/properties/criteria/title
* [x] /definitions/Award/properties/requirementResponses/title
* [x] /definitions/Award/properties/requirementResponses/description
* [x] /definitions/Contract/properties/requirementResponses/title
* [x] /definitions/Contract/properties/requirementResponses/description
* [x] /definitions/Criterion/properties/id/title
* [x] /definitions/Criterion/properties/title/title
* [x] /definitions/Criterion/properties/description/title
* [x] /definitions/Criterion/properties/source/title
* [x] /definitions/Criterion/properties/relatesTo/title
* [x] /definitions/Criterion/properties/relatedItem/title
* [x] /definitions/RequirementGroup/properties/id/title
* [x] /definitions/RequirementGroup/properties/description/title
* [x] /definitions/Requirement/properties/pattern/title
* [x] /definitions/Requirement/properties/expectedValue/title
* [x] /definitions/Requirement/properties/minValue/title
* [x] /definitions/Requirement/properties/maxValue/title
* [x] /definitions/Requirement/properties/period/title
* [x] /definitions/RequirementResponse/properties/id/title
* [x] /definitions/RequirementResponse/properties/title/title
* [x] /definitions/RequirementResponse/properties/description/title
* [x] /definitions/RequirementResponse/properties/value/title
* [x] /definitions/RequirementResponse/properties/period/title

### Other

api_extension/release-schema.json

* [x] /properties/packageMetadata/title
* [x] /properties/packageMetadata/description
* [x] /properties/packageMetadata/properties/publishedDate/title
* [x] /properties/packageMetadata/properties/publisher/title
* [x] /properties/packageMetadata/properties/license/title
* [x] /properties/packageMetadata/properties/publicationPolicy/title

ocds_budget_breakdown_extension/release-schema.json

* [x] /definitions/BudgetBreakdown/properties/id/title
* [x] /definitions/BudgetBreakdown/properties/amount/title

**Comment by jpmckinney** [comment]
@timgdavies How should we proceed to fill in these fields (not urgent, just in terms of process)? Or should a field `description` be optional in an extension?

**Comment by timgdavies** [comment]
These should be required.

Some of these are part of core extensions, so would need to be updated as part of a bug-fix release. 

Others we can just update ad-hoc, so I'm putting this on ToDo list for schema work next week.

**Comment by timgdavies** [comment]
Location and lots are core extensions, so I'll work on those now as part of 1.1.3 prep:

* [ ] ocds_location_extension/release-schema.json is missing /definitions/Item/properties/deliveryLocation/description
* [ ] ocds_location_extension/release-schema.json is missing /definitions/Item/properties/deliveryAddress/description
* [ ] ocds_location_extension/release-schema.json is missing /definitions/Location/properties/gazetteer/title
* [ ] ocds_location_extension/release-schema.json is missing /definitions/Location/properties/gazetteer/description
* [ ] ocds_lots_extension/release-schema.json is missing /definitions/Tender/properties/lotDetails/title
* [ ] ocds_lots_extension/release-schema.json is missing /definitions/Tender/properties/lotDetails/description

**Comment by timgdavies** [comment]
I've added descriptions for location and lots extensions.

This did surface one issue in the lots extension, where /definitions/Tender/properties/lotDetails/ uses a $ref just for layout of the components of the lot (rather than in the case where there is an array, and then objects in that array). 

This means the addition descriptions added (for which I duplicated the descriptions from the target) are redundant. It is possible we should refactor the lots extension to remove this reference, unless there are likely to be cases where LotDetails are re-used by some other extension. 

This should inform our guidance about how to structure extensions, and when to use $ref

**Comment by jpmckinney** [comment]
If we don't presently anticipate reuse of LotDetails, then we should avoid the `$ref`. Shall we do that in https://github.com/open-contracting/ocds_lots_extension/pull/16 ?

**Comment by jpmckinney** [comment]
Noting that once this issue is closed, I can uncomment a test.

**Comment by jpmckinney** [comment]
@timgdavies ocds_participationFee_extension is also a core extension. Could you add its three missing title/description properties? (see issue description)

**Comment by jpmckinney** [comment]
Removing 1.1.3 milestone, as all core extensions now fixed.

**Comment by jpmckinney** [comment]
Do we want to fix this as part of PPPs cleanup? @duncandewhurst

**Comment by duncandewhurst** [comment]
I've added the missing fields for all the PPP extensions, in one instance (budget and projects extension) I noted the same issue with use of $ref as Tim mentioned above so amended the schema accordingly.

I also noticed we aren't consistent with whether we include the parent object name in the **title** of fields. The [style guide](http://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide/?highlight=style#schema-style-guide) says we shouldn't do that in **names** of properties and objects but doesn't specify an approach for field titles.

I've used whatever seemed most appropriate, but think that in general we probably should include parent object names in titles, since some users will work with the flattened schema without seeing the full field path.

**Comment by jpmckinney** [comment]
I think that may indicate an opportunity to improve the flattened schema (e.g. add a column with the name of the containing object), rather than make all field titles more verbose. There are use cases for which verbosity is undesirable (e.g. the automatic generation of a form or UI will repeat the object name, making tasks like finding the desired field slower, because in general any offset of the target word from the start of the line causes slower task times in user tests).

**Comment by jpmckinney** [comment]
I have a commit for API extension. This is done now.
