### ISSUE TITLE
META: Add closed codelist for enum

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#43]
Related: open-contracting/standard#582 https://github.com/open-contracting/standard-maintenance-scripts/issues/16

The following extensions have `enum` fields without an associated closed codelist:

* [x] **ocds_charges_extension**: /definitions/Charge/properties/paidBy
* [x] **ocds_location_extension**: /definitions/Location/properties/geometry/properties/type
* [x] **ocds_partyDetails_scale_extension**: /definitions/Organization/properties/details/properties/scale
* [x] **ocds_tariffs_extension**: /definitions/Tariff/properties/paidBy

And in the standard:

* [x] **record-package-schema.json**: /definitions/record/properties/releases/oneOf/0/items/properties/tag/items

**Comment by jpmckinney** [comment]
These fixes will need to be done manually to set an appropriate CSV filename, and to fill in the titles and descriptions of the codes.

**Comment by timgdavies** [comment]
Fixes merged on extensions, and awaiting deployment on main schema as part of [OCDS 1.1.3-dev](https://github.com/open-contracting/standard/commit/a75c1c50379881f618df97ed3b9967297ed2edca)

**Comment by jpmckinney** [comment]
Closing, though 1.1.3-dev technically needs to be merged for issue to be truly closed.
