### ISSUE TITLE
META: Make appropriate fields nullable

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#50]
Related: https://github.com/open-contracting/standard/issues/630

# Core

**ocds_bid_extension**

* [x] required but nullable ['object', 'null'] at /definitions/BidsStatistic
* [x] required but nullable ['string', 'null'] at /definitions/BidsStatistic/properties/id
* [x] required but nullable ['string', 'null'] at /definitions/BidsStatistic/properties/measure
* [x] required but nullable ['number', 'null'] at /definitions/BidsStatistic/properties/value
* [x] optional but non-nullable ['array'] at /definitions/Bids/properties/statistics

**ocds_enquiry_extension**

* [x] optional but non-nullable string at /definitions/Enquiry/properties/date

**ocds_location_extension**

* [x] optional but non-nullable object at /definitions/Location/properties/geometry
* [x] optional but non-nullable object at /definitions/Location/properties/gazetteer

**ocds_lots_extension**

* ~~optional but non-nullable string at /definitions/Lot/properties/id~~ #53
* ~~optional but non-nullable string at /definitions/LotGroup/properties/id~~ #53

**ocds_participationFee_extension**

* [x] optional but non-nullable string at /definitions/ParticipationFee/properties/description

# Community

### PPPs

**ocds-riskAllocation-extension**

* ~~optional but non-nullable ['string', 'integer'] at /definitions/Risk/properties/id~~ #53

**ocds-shareholders-extension**

* [x] optional but non-nullable object at /definitions/Organization/properties/beneficialOwnership
* [x] optional but non-nullable string at /definitions/Organization/properties/beneficialOwnership/properties/description
* ~~optional but non-nullable ['string'] at /definitions/Shareholder/properties/id~~ #53

**ocds_charges_extension**

* ~~optional but non-nullable string at /definitions/Charge/properties/id~~ #53

**ocds_finance_extension**

* [x] optional but non-nullable object at /definitions/Finance/properties/interestRate

**ocds_metrics_extension**

* ~~optional but non-nullable ['string'] at /definitions/Metric/properties/id~~ #53
* ~~optional but non-nullable string at /definitions/Observation/properties/id~~ #53
* [x] optional but non-nullable object at /definitions/Observation/properties/dimensions
* [x] optional but non-nullable string at /definitions/Observation/properties/dimensions/patternProperties/^.*

**ocds_performance_failures**

* ~~optional but non-nullable string at /definitions/PerformanceFailure/properties/id~~ #53
* [x] optional but non-nullable object at /definitions/PerformanceFailure/properties/period

**ocds_requirements_extension**

* [x] optional but non-nullable string at /definitions/Criterion/properties/source
* [x] optional but non-nullable string at /definitions/Criterion/properties/relatesTo
* [x] optional but non-nullable string at /definitions/RequirementReference/properties/title

**ocds_tariffs_extension**

* ~~optional but non-nullable string at /definitions/Tariff/properties/id~~ #53
* [x] optional but non-nullable object at /definitions/Tariff/properties/dimensions
* [x] optional but non-nullable string at /definitions/Tariff/properties/dimensions/patternProperties/^.*

### Other

**api_extension**

* [ ] optional but non-nullable object at /properties/packageMetadata
* [ ] optional but non-nullable string at /properties/packageMetadata/properties/uri
* [ ] optional but non-nullable string at /properties/packageMetadata/properties/publishedDate
* [ ] optional but non-nullable object at /properties/packageMetadata/properties/publisher

**ocds_extendsContractID_extension**

* [x] optional but non-nullable ['string'] at /definitions/Contract/properties/extendsContractID

**Comment by jpmckinney** [comment]
@timgdavies I think a lot of the `id` properties should be made `required` to reduce the number of errors here. For the rest, we can add/remove "null" from "type".

**Comment by jpmckinney** [comment]
Noting that once these issues are fixed, I'll comment out a test; otherwise, too many extensions will fail until this issue is fixed.

**Comment by jpmckinney** [comment]
Removing 1.1.3 milestone, as all core extensions now covered.

**Comment by jpmckinney** [comment]
Do we want to fix this as part of PPPs cleanup? @duncandewhurst

**Comment by duncandewhurst** [comment]
@jpmckinney - in working through updates to the PPP extensions, I noticed that `milestoneReference` in the metrics extension is an optional object, albeit with a required `id` property when the object is present, which is not nullable:

```json
     "MilestoneReference": {
      "type": "object",
      "title": "Milestone Reference",
      "description": "A block used to reference a milestone, including the ID and title of the milestone being referenced.",
      "required": [
        "id"
      ],
```

Any reason that hasn't be included in the list of objects to make nullable?

**Comment by duncandewhurst** [comment]
@jpmckinney okay, makes sense

So to close this issue we just need to make the fields in the api_extension nullable, but I notice that those are required fields when the extension isn't used and they are included in the release package meta data 

@kindly should `packageMetaData/uri`, `packageMetaData/publisher` and `packageMetaData/publishedDate` be optional in the api extension even though they are required in a release package?

**Comment by jpmckinney** [comment]
We can make an exception for the API extension - there are already several exceptions to how it's treated.

**Comment by jpmckinney** [comment]
I've made those exceptions. The API extension is not like the other extensions; there's no use case for nullable fields as there is no merging. Closing.
