### ISSUE TITLE
META: Define codelist column headers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#57]
The required fields are:

* Code
* Title
* Description (except currency.csv)

Fewer files use `Title_en` and `Description_en`. *Why do we have both pairs?* We should be consistent.

We also have:

* Category: *see https://github.com/open-contracting/ocds-extensions/issues/56*
* Deprecated (awardCriteria.csv only)
* Extension (OCDS for PPPs only): "OCDS Core" or extension title
* Section (documentType.csv only): *inconsistently using `,` or `/` for multiple sections in PPPs*
* Source: URI format *except in riskCategory.csv*
* Valid Until (currency.csv only)
* URI_Pattern (locationGazetteers.csv only)

*Re: URI_Pattern, I think codelist headers should use spaces, not underscores.*

Re: Code, it's mostly lowerCamelCase, but there's also:

* `""` in partyScale.csv
* `date-time` in dataType.csv
* UpperCamelCase `MultiPoint`, etc. in geometryType.csv
* all-caps `ISO2`, etc. in locationGazetteers.csv

**Comment by jpmckinney** [comment]
I wrote some initial definitions in https://github.com/open-contracting/standard-maintenance-scripts/blob/master/schema/codelist-schema.json but the italicized issues and questions above should be resolved, so that I can close https://github.com/open-contracting/standard-maintenance-scripts/issues/63

**Comment by jpmckinney** [comment]
To summarize potential issues:

* [ ] Why do we have both pair `Title`/`Description` and `Title_en`/`Description_en`? Which one should we use consistently?
* [ ] `Section` inconsistently uses `, ` or `/` to separate section names. Which one should we use consistently?
* [ ] `Source` is a URL, except in [riskCategory.csv](https://github.com/open-contracting/ocds-riskAllocation-extension/blob/master/codelists/riskCategory.csv). Should we use URLs consistently?
* [ ] Rename `URI_Pattern` to `URI Pattern`.
* `Category` is used inconsistently (see #56)

**Comment by jpmckinney** [comment]
@timgdavies Let me know your opinion on the above. It would be nice to do this clean up in 1.1.3 if possible.

**Comment by jpmckinney** [comment]
I went ahead and renamed to `Title`, `Description`, `URI Pattern` in my PR. I could find no documentation about codelist format anywhere.
